language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls

